[package]
name = "rats"
version = "0.1.0"
authors = ["Darin Minamoto <darinm223@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
